//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class affairflow
    {
        public affairflow()
        {
            this.smsabout = new HashSet<smsabout>();
            this.userright = new HashSet<userright>();
        }
    
        public int FLOWID { get; set; }
        public int AFFAIRID { get; set; }
        public string FLOWCODE { get; set; }
        public string FLOWNAME { get; set; }
        public int PARENTFLOW { get; set; }
        public int AF_ORG { get; set; }
        public int NEXTFLOW { get; set; }
        public float TIMELIMIT { get; set; }
        public int FLOWEORDER { get; set; }
        public int FLOWERTYPE { get; set; }
        public int VALIDITYTORESULT { get; set; }
        public int CANEDIT { get; set; }
        public int VALID { get; set; }
        public string RESERVED1 { get; set; }
        public string RESERVED2 { get; set; }
        public string RESERVED3 { get; set; }
        public string RESERVED4 { get; set; }
        public string RESERVED5 { get; set; }
    
        public virtual dic_standardproc dic_standardproc { get; set; }
        public virtual dic_competentauth dic_competentauth { get; set; }
        public virtual affairs affairs { get; set; }
        public virtual ICollection<smsabout> smsabout { get; set; }
        public virtual ICollection<userright> userright { get; set; }
    }
}
