//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class affairs
    {
        public affairs()
        {
            this.af_businesssystems = new HashSet<af_businesssystems>();
            this.affairconfig = new HashSet<affairconfig>();
            this.affairdifficulties = new HashSet<affairdifficulties>();
            this.affairflow = new HashSet<affairflow>();
            this.affairguide = new HashSet<affairguide>();
            this.affairinfo = new HashSet<affairinfo>();
            this.dic_standardreplayfile = new HashSet<dic_standardreplayfile>();
            this.repository_base = new HashSet<repository_base>();
            this.lb_affairsclassify = new HashSet<lb_affairsclassify>();
            this.materials_byobject = new HashSet<materials_byobject>();
            this.materials_details = new HashSet<materials_details>();
            this.operationguide = new HashSet<operationguide>();
            this.bg_answergroup = new HashSet<bg_answergroup>();
            this.bg_answers = new HashSet<bg_answers>();
            this.bg_questions = new HashSet<bg_questions>();
            this.userpower = new HashSet<userpower>();
        }
    
        public int AFFAIRID { get; set; }
        public string AFFAIRCODE { get; set; }
        public string AFFAIRNAME { get; set; }
        public string AF_ABBREVIATION { get; set; }
        public Nullable<int> AF_TYPE { get; set; }
        public int AF_LEVEL { get; set; }
        public int AF_DEPARTMENT { get; set; }
        public float TIMELIMIT { get; set; }
        public int TIMELIMITTYPE { get; set; }
        public int AF_PARENT { get; set; }
        public int VALID { get; set; }
        public string RESERVED1 { get; set; }
        public string RESERVED2 { get; set; }
        public string RESERVED3 { get; set; }
        public string RESERVED4 { get; set; }
        public string RESERVED5 { get; set; }
        public Nullable<bool> LIMIT_HANDLE_TIME { get; set; }
        public Nullable<System.DateTime> HANDLE_BEGIN_TIME { get; set; }
        public Nullable<System.DateTime> HANDLE_END_TIME { get; set; }
        public Nullable<bool> LIMIT_AUDITIN_TIME { get; set; }
        public Nullable<System.DateTime> AUDITING_BEGING_TIME { get; set; }
        public Nullable<System.DateTime> AUDITING_END_TIME { get; set; }
        public Nullable<int> AUDITING_BEGIN_DAY { get; set; }
        public Nullable<int> AUDITING_DAY_NUMBER { get; set; }
    
        public virtual ICollection<af_businesssystems> af_businesssystems { get; set; }
        public virtual ICollection<affairconfig> affairconfig { get; set; }
        public virtual ICollection<affairdifficulties> affairdifficulties { get; set; }
        public virtual ICollection<affairflow> affairflow { get; set; }
        public virtual ICollection<affairguide> affairguide { get; set; }
        public virtual ICollection<affairinfo> affairinfo { get; set; }
        public virtual ICollection<dic_standardreplayfile> dic_standardreplayfile { get; set; }
        public virtual dic_timelimittype dic_timelimittype { get; set; }
        public virtual dic_af_level dic_af_level { get; set; }
        public virtual dic_competentauth dic_competentauth { get; set; }
        public virtual dic_affairtype dic_affairtype { get; set; }
        public virtual ICollection<repository_base> repository_base { get; set; }
        public virtual ICollection<lb_affairsclassify> lb_affairsclassify { get; set; }
        public virtual ICollection<materials_byobject> materials_byobject { get; set; }
        public virtual ICollection<materials_details> materials_details { get; set; }
        public virtual ICollection<operationguide> operationguide { get; set; }
        public virtual ICollection<bg_answergroup> bg_answergroup { get; set; }
        public virtual ICollection<bg_answers> bg_answers { get; set; }
        public virtual ICollection<bg_questions> bg_questions { get; set; }
        public virtual ICollection<userpower> userpower { get; set; }
    }
}
