//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class affair_check
    {
        public affair_check()
        {
            this.affair_attach = new HashSet<affair_attach>();
            this.affair_check_message = new HashSet<affair_check_message>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AffairId { get; set; }
        public int ApplyUserID { get; set; }
        public string ApplyAction { get; set; }
        public Nullable<System.DateTime> ApplyTime { get; set; }
        public Nullable<int> CheckState { get; set; }
        public string CheckMessage { get; set; }
        public Nullable<int> Step { get; set; }
        public Nullable<int> CheckUser { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
    
        public virtual ICollection<affair_attach> affair_attach { get; set; }
        public virtual ICollection<affair_check_message> affair_check_message { get; set; }
    }
}
