//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class affair_role
    {
        public affair_role()
        {
            this.affair_manager_role_value = new HashSet<affair_manager_role_value>();
            this.affair_role_channel_value = new HashSet<affair_role_channel_value>();
        }
    
        public int ID { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> isvalid { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> RoleType { get; set; }
    
        public virtual ICollection<affair_manager_role_value> affair_manager_role_value { get; set; }
        public virtual ICollection<affair_role_channel_value> affair_role_channel_value { get; set; }
    }
}
