//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class affair_manager_role_value
    {
        public int ID { get; set; }
        public int RoleId { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public int UserId { get; set; }
    
        public virtual affair_manager affair_manager { get; set; }
        public virtual affair_role affair_role { get; set; }
    }
}
