//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class affair_edit
    {
        public int ID { get; set; }
        public string AFFAIRCODE { get; set; }
        public string AFFAIRNAME { get; set; }
        public string AF_ABBREVIATION { get; set; }
        public Nullable<int> AF_TYPE { get; set; }
        public int AF_LEVEL { get; set; }
        public int AF_DEPARTMENT { get; set; }
        public float TIMELIMIT { get; set; }
        public int TIMELIMITTYPE { get; set; }
        public int AF_PARENT { get; set; }
        public int VALID { get; set; }
        public string RESERVED1 { get; set; }
        public string RESERVED2 { get; set; }
        public string RESERVED3 { get; set; }
        public string RESERVED4 { get; set; }
        public string RESERVED5 { get; set; }
        public Nullable<int> State { get; set; }
        public int AFFAIRID { get; set; }
        public string Action { get; set; }
    }
}
