//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agentinfo
    {
        public int CURRAFFAIRID { get; set; }
        public Nullable<int> AGENT_DOC_TYPE { get; set; }
        public string AGENT_IDNUMBER { get; set; }
        public string AGENT_NAME { get; set; }
        public Nullable<int> AGENT_SEX { get; set; }
        public Nullable<System.DateTime> AGENT_BIRTHDAY { get; set; }
        public string AGENT_PHONE { get; set; }
        public string AGENT_MOBLEPHONE { get; set; }
        public string RESIDENCEADDRESS { get; set; }
        public string LIVEADDRESS { get; set; }
        public Nullable<int> VALID { get; set; }
    
        public virtual affairinfo affairinfo { get; set; }
        public virtual dic_docmenttype dic_docmenttype { get; set; }
    }
}
