//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditattachment
    {
        public int ID { get; set; }
        public int CURR_AFFAIRID { get; set; }
        public string ATTACHMENTPATH { get; set; }
        public string FULLNAME { get; set; }
        public Nullable<int> STANDARDFILEID { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<int> UPDATEOPERATOR { get; set; }
        public Nullable<int> VALID { get; set; }
    
        public virtual affairinfo affairinfo { get; set; }
        public virtual dic_standardreplayfile dic_standardreplayfile { get; set; }
        public virtual sy_user sy_user { get; set; }
    }
}
