//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class configvaluegroup
    {
        public configvaluegroup()
        {
            this.configvalueforkey = new HashSet<configvalueforkey>();
            this.serviceversion = new HashSet<serviceversion>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SERVICEWINDOWID { get; set; }
        public string GROUPDESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    
        public virtual ICollection<configvalueforkey> configvalueforkey { get; set; }
        public virtual servicewindow servicewindow { get; set; }
        public virtual ICollection<serviceversion> serviceversion { get; set; }
    }
}
