//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class configvalueforkey
    {
        public int ID { get; set; }
        public Nullable<int> KEYID { get; set; }
        public Nullable<int> GROUPID { get; set; }
        public string VALUE { get; set; }
    
        public virtual configkey configkey { get; set; }
        public virtual configvaluegroup configvaluegroup { get; set; }
    }
}
