//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactrecord
    {
        public long ID { get; set; }
        public int CURR_AFFAIRID { get; set; }
        public string CONTACTCODE { get; set; }
        public int ORDERNUM { get; set; }
        public string IDNUMBER { get; set; }
        public int P_DOC_TYPE { get; set; }
    
        public virtual affairinfo affairinfo { get; set; }
    }
}
