//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dic_competentauth
    {
        public dic_competentauth()
        {
            this.affairflow = new HashSet<affairflow>();
            this.affairs = new HashSet<affairs>();
            this.st_question = new HashSet<st_question>();
        }
    
        public int ID { get; set; }
        public string FULLNAME { get; set; }
        public string ABBREVIATION { get; set; }
        public int VALID { get; set; }
    
        public virtual ICollection<affairflow> affairflow { get; set; }
        public virtual ICollection<affairs> affairs { get; set; }
        public virtual ICollection<st_question> st_question { get; set; }
    }
}
