//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dic_town
    {
        public dic_town()
        {
            this.affairinfo = new HashSet<affairinfo>();
            this.commonproblem = new HashSet<commonproblem>();
            this.dic_committee = new HashSet<dic_committee>();
            this.requestwindow = new HashSet<requestwindow>();
            this.servicewindow = new HashSet<servicewindow>();
            this.notice = new HashSet<notice>();
            this.virtualmachinelist = new HashSet<virtualmachinelist>();
            this.linebusinesssys = new HashSet<linebusinesssys>();
            this.transportfile = new HashSet<transportfile>();
            this.materialtakeinfo = new HashSet<materialtakeinfo>();
            this.sy_user = new HashSet<sy_user>();
            this.systemconfig = new HashSet<systemconfig>();
            this.touchnotice = new HashSet<touchnotice>();
            this.transportfile_complete = new HashSet<transportfile_complete>();
            this.transportfile_copy = new HashSet<transportfile_copy>();
        }
    
        public int CODE { get; set; }
        public string CNAME { get; set; }
        public int PARENT { get; set; }
        public int VALID { get; set; }
    
        public virtual ICollection<affairinfo> affairinfo { get; set; }
        public virtual ICollection<commonproblem> commonproblem { get; set; }
        public virtual ICollection<dic_committee> dic_committee { get; set; }
        public virtual dic_counties dic_counties { get; set; }
        public virtual ICollection<requestwindow> requestwindow { get; set; }
        public virtual ICollection<servicewindow> servicewindow { get; set; }
        public virtual ICollection<notice> notice { get; set; }
        public virtual ICollection<virtualmachinelist> virtualmachinelist { get; set; }
        public virtual ICollection<linebusinesssys> linebusinesssys { get; set; }
        public virtual ICollection<transportfile> transportfile { get; set; }
        public virtual ICollection<materialtakeinfo> materialtakeinfo { get; set; }
        public virtual ICollection<sy_user> sy_user { get; set; }
        public virtual ICollection<systemconfig> systemconfig { get; set; }
        public virtual ICollection<touchnotice> touchnotice { get; set; }
        public virtual ICollection<transportfile_complete> transportfile_complete { get; set; }
        public virtual ICollection<transportfile_copy> transportfile_copy { get; set; }
    }
}
