//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dic_userrole
    {
        public dic_userrole()
        {
            this.sy_user = new HashSet<sy_user>();
        }
    
        public int CODE { get; set; }
        public string CNAME { get; set; }
        public int VALID { get; set; }
    
        public virtual ICollection<sy_user> sy_user { get; set; }
    }
}
