//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dic_violatebehavior
    {
        public dic_violatebehavior()
        {
            this.violateinfo = new HashSet<violateinfo>();
        }
    
        public int CODE { get; set; }
        public string DVALUE { get; set; }
        public Nullable<int> VALID { get; set; }
    
        public virtual ICollection<violateinfo> violateinfo { get; set; }
    }
}
