//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dic_town
    {
        public dic_town()
        {
            this.affairinfo = new HashSet<affairinfo>();
            this.dic_committee = new HashSet<dic_committee>();
            this.materialtakeinfo = new HashSet<materialtakeinfo>();
        }
    
        public int CODE { get; set; }
        public string CNAME { get; set; }
        public int PARENT { get; set; }
        public int VALID { get; set; }
    
        public virtual ICollection<affairinfo> affairinfo { get; set; }
        public virtual ICollection<dic_committee> dic_committee { get; set; }
        public virtual ICollection<materialtakeinfo> materialtakeinfo { get; set; }
    }
}
