//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dic_yushenstate
    {
        public dic_yushenstate()
        {
            this.yu_shen = new HashSet<yu_shen>();
        }
    
        public int ID { get; set; }
        public string StateName { get; set; }
        public Nullable<int> Valid { get; set; }
    
        public virtual ICollection<yu_shen> yu_shen { get; set; }
    }
}
