//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dic_receivetype
    {
        public dic_receivetype()
        {
            this.materialtakeinfo = new HashSet<materialtakeinfo>();
            this.materials_details = new HashSet<materials_details>();
        }
    
        public int MATCODE { get; set; }
        public string MATNAME { get; set; }
        public int VALID { get; set; }
    
        public virtual ICollection<materialtakeinfo> materialtakeinfo { get; set; }
        public virtual ICollection<materials_details> materials_details { get; set; }
    }
}
