//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dic_standardproc
    {
        public dic_standardproc()
        {
            this.affairflow = new HashSet<affairflow>();
        }
    
        public string FLOWCODE { get; set; }
        public string PNAME { get; set; }
        public int PLEVEL { get; set; }
        public int VALID { get; set; }
    
        public virtual ICollection<affairflow> affairflow { get; set; }
    }
}
