//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dic_djaffairs
    {
        public int ID { get; set; }
        public string AFFAIRCODE { get; set; }
        public string AFFAIRNAME { get; set; }
        public string PARENTAFFAIRID { get; set; }
        public string CHILDAFFAIRID { get; set; }
        public int TOWNID { get; set; }
        public string TOWNCODE { get; set; }
        public string DEPTCODE { get; set; }
    }
}
