//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int ID { get; set; }
        public string PhoneNumber { get; set; }
        public string Suggestions { get; set; }
        public int TypeID { get; set; }
        public string MachineNumber { get; set; }
    
        public virtual dic_feedbacktype dic_feedbacktype { get; set; }
    }
}
