//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jianzhengEntities : DbContext
    {
        public jianzhengEntities()
            : base("name=jianzhengEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<affairinfo> affairinfo { get; set; }
        public DbSet<businessinfo> businessinfo { get; set; }
        public DbSet<dic_committee> dic_committee { get; set; }
        public DbSet<dic_town> dic_town { get; set; }
        public DbSet<materialtakeinfo> materialtakeinfo { get; set; }
        public DbSet<tpersons> tpersons { get; set; }
        public DbSet<user_report> user_report { get; set; }
        public DbSet<view_detail> view_detail { get; set; }
        public DbSet<view_person_detail> view_person_detail { get; set; }
    }
}
