//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jianzhengEntities : DbContext
    {
        public jianzhengEntities()
            : base("name=jianzhengEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<affairinfo> affairinfo { get; set; }
        public virtual DbSet<businessinfo> businessinfo { get; set; }
        public virtual DbSet<dic_committee> dic_committee { get; set; }
        public virtual DbSet<dic_town> dic_town { get; set; }
        public virtual DbSet<tpersons> tpersons { get; set; }
        public virtual DbSet<user_report> user_report { get; set; }
        public virtual DbSet<view_detail> view_detail { get; set; }
    }
}
