//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jianzhengEntities : DbContext
    {
        public jianzhengEntities()
            : base("name=jianzhengEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<addressbook> addressbook { get; set; }
        public virtual DbSet<af_businesssystems> af_businesssystems { get; set; }
        public virtual DbSet<affair_attach> affair_attach { get; set; }
        public virtual DbSet<affair_check> affair_check { get; set; }
        public virtual DbSet<affair_check_message> affair_check_message { get; set; }
        public virtual DbSet<affair_edit> affair_edit { get; set; }
        public virtual DbSet<affair_manager> affair_manager { get; set; }
        public virtual DbSet<affair_manager_role_value> affair_manager_role_value { get; set; }
        public virtual DbSet<affair_role> affair_role { get; set; }
        public virtual DbSet<affair_role_channel_value> affair_role_channel_value { get; set; }
        public virtual DbSet<affairconfig> affairconfig { get; set; }
        public virtual DbSet<affairdifficulties> affairdifficulties { get; set; }
        public virtual DbSet<affairflow> affairflow { get; set; }
        public virtual DbSet<affairguide> affairguide { get; set; }
        public virtual DbSet<affairinfo> affairinfo { get; set; }
        public virtual DbSet<affairs> affairs { get; set; }
        public virtual DbSet<agentinfo> agentinfo { get; set; }
        public virtual DbSet<auditattachment> auditattachment { get; set; }
        public virtual DbSet<auditrecords> auditrecords { get; set; }
        public virtual DbSet<bg_answergroup> bg_answergroup { get; set; }
        public virtual DbSet<bg_answers> bg_answers { get; set; }
        public virtual DbSet<bg_questions> bg_questions { get; set; }
        public virtual DbSet<bg_takemat> bg_takemat { get; set; }
        public virtual DbSet<businessguide> businessguide { get; set; }
        public virtual DbSet<businessinfo> businessinfo { get; set; }
        public virtual DbSet<clientversion> clientversion { get; set; }
        public virtual DbSet<collection_notice> collection_notice { get; set; }
        public virtual DbSet<commonproblem> commonproblem { get; set; }
        public virtual DbSet<configkey> configkey { get; set; }
        public virtual DbSet<configvalueforkey> configvalueforkey { get; set; }
        public virtual DbSet<configvaluegroup> configvaluegroup { get; set; }
        public virtual DbSet<contactrecord> contactrecord { get; set; }
        public virtual DbSet<dic_af_level> dic_af_level { get; set; }
        public virtual DbSet<dic_affairtype> dic_affairtype { get; set; }
        public virtual DbSet<dic_committee> dic_committee { get; set; }
        public virtual DbSet<dic_competentauth> dic_competentauth { get; set; }
        public virtual DbSet<dic_counties> dic_counties { get; set; }
        public virtual DbSet<dic_datadirectory> dic_datadirectory { get; set; }
        public virtual DbSet<dic_djaffairs> dic_djaffairs { get; set; }
        public virtual DbSet<dic_docmenttype> dic_docmenttype { get; set; }
        public virtual DbSet<dic_feedbacktype> dic_feedbacktype { get; set; }
        public virtual DbSet<dic_locdepartment> dic_locdepartment { get; set; }
        public virtual DbSet<dic_receivetype> dic_receivetype { get; set; }
        public virtual DbSet<dic_servicestatus> dic_servicestatus { get; set; }
        public virtual DbSet<dic_standardproc> dic_standardproc { get; set; }
        public virtual DbSet<dic_standardreplayfile> dic_standardreplayfile { get; set; }
        public virtual DbSet<dic_stateofaffairs> dic_stateofaffairs { get; set; }
        public virtual DbSet<dic_timelimittype> dic_timelimittype { get; set; }
        public virtual DbSet<dic_town> dic_town { get; set; }
        public virtual DbSet<dic_transtype> dic_transtype { get; set; }
        public virtual DbSet<dic_userlevel> dic_userlevel { get; set; }
        public virtual DbSet<dic_userrole> dic_userrole { get; set; }
        public virtual DbSet<dic_violatebehavior> dic_violatebehavior { get; set; }
        public virtual DbSet<dic_yushenstate> dic_yushenstate { get; set; }
        public virtual DbSet<feedback> feedback { get; set; }
        public virtual DbSet<grapping> grapping { get; set; }
        public virtual DbSet<lb_affairsclassify> lb_affairsclassify { get; set; }
        public virtual DbSet<lb_classify> lb_classify { get; set; }
        public virtual DbSet<lb_classifyproject> lb_classifyproject { get; set; }
        public virtual DbSet<linebusiness_count> linebusiness_count { get; set; }
        public virtual DbSet<linebusinesssys> linebusinesssys { get; set; }
        public virtual DbSet<lineelement> lineelement { get; set; }
        public virtual DbSet<lineweburl> lineweburl { get; set; }
        public virtual DbSet<loginlog> loginlog { get; set; }
        public virtual DbSet<materials_byobject> materials_byobject { get; set; }
        public virtual DbSet<materials_details> materials_details { get; set; }
        public virtual DbSet<materialtakeinfo> materialtakeinfo { get; set; }
        public virtual DbSet<materialtransfer> materialtransfer { get; set; }
        public virtual DbSet<messagepoints1> messagepoints1 { get; set; }
        public virtual DbSet<mtrecord> mtrecord { get; set; }
        public virtual DbSet<notice> notice { get; set; }
        public virtual DbSet<noticeattachment> noticeattachment { get; set; }
        public virtual DbSet<operationguide> operationguide { get; set; }
        public virtual DbSet<personbase> personbase { get; set; }
        public virtual DbSet<report_syinfo> report_syinfo { get; set; }
        public virtual DbSet<report_userinfo> report_userinfo { get; set; }
        public virtual DbSet<repository> repository { get; set; }
        public virtual DbSet<repository_base> repository_base { get; set; }
        public virtual DbSet<repository_base_attachment> repository_base_attachment { get; set; }
        public virtual DbSet<repositoryanswers> repositoryanswers { get; set; }
        public virtual DbSet<requestwindow> requestwindow { get; set; }
        public virtual DbSet<serviceversion> serviceversion { get; set; }
        public virtual DbSet<servicewindow> servicewindow { get; set; }
        public virtual DbSet<smsabout> smsabout { get; set; }
        public virtual DbSet<st_answer> st_answer { get; set; }
        public virtual DbSet<st_exam> st_exam { get; set; }
        public virtual DbSet<st_examqf> st_examqf { get; set; }
        public virtual DbSet<st_faq> st_faq { get; set; }
        public virtual DbSet<st_paper> st_paper { get; set; }
        public virtual DbSet<st_paperquestion> st_paperquestion { get; set; }
        public virtual DbSet<st_question> st_question { get; set; }
        public virtual DbSet<st_qwtype> st_qwtype { get; set; }
        public virtual DbSet<st_reply> st_reply { get; set; }
        public virtual DbSet<st_train> st_train { get; set; }
        public virtual DbSet<st_user_exam> st_user_exam { get; set; }
        public virtual DbSet<st_userfav> st_userfav { get; set; }
        public virtual DbSet<st_video> st_video { get; set; }
        public virtual DbSet<sy_user> sy_user { get; set; }
        public virtual DbSet<sysmsgnotification> sysmsgnotification { get; set; }
        public virtual DbSet<sysmsgtype> sysmsgtype { get; set; }
        public virtual DbSet<systemconfig> systemconfig { get; set; }
        public virtual DbSet<temp_jw> temp_jw { get; set; }
        public virtual DbSet<temp_ri> temp_ri { get; set; }
        public virtual DbSet<touchnotice> touchnotice { get; set; }
        public virtual DbSet<transfer_table> transfer_table { get; set; }
        public virtual DbSet<transportfile> transportfile { get; set; }
        public virtual DbSet<transportfile_complete> transportfile_complete { get; set; }
        public virtual DbSet<transportfile_copy> transportfile_copy { get; set; }
        public virtual DbSet<user_remark> user_remark { get; set; }
        public virtual DbSet<user_report> user_report { get; set; }
        public virtual DbSet<userpower> userpower { get; set; }
        public virtual DbSet<userright> userright { get; set; }
        public virtual DbSet<versionrecord> versionrecord { get; set; }
        public virtual DbSet<violateattachment> violateattachment { get; set; }
        public virtual DbSet<violateinfo> violateinfo { get; set; }
        public virtual DbSet<virtualmachinelist> virtualmachinelist { get; set; }
        public virtual DbSet<yu_shen> yu_shen { get; set; }
        public virtual DbSet<yu_shen_material> yu_shen_material { get; set; }
        public virtual DbSet<yu_yue> yu_yue { get; set; }
        public virtual DbSet<znsgmachine> znsgmachine { get; set; }
        public virtual DbSet<znsgsitelog> znsgsitelog { get; set; }
        public virtual DbSet<zxloginlog> zxloginlog { get; set; }
        public virtual DbSet<zxzhconfig> zxzhconfig { get; set; }
        public virtual DbSet<st_apply> st_apply { get; set; }
        public virtual DbSet<v_affinfo> v_affinfo { get; set; }
        public virtual DbSet<v_affplan> v_affplan { get; set; }
        public virtual DbSet<v_examquestion> v_examquestion { get; set; }
        public virtual DbSet<v_linema> v_linema { get; set; }
        public virtual DbSet<v_lines> v_lines { get; set; }
        public virtual DbSet<v_manager> v_manager { get; set; }
        public virtual DbSet<v_material> v_material { get; set; }
        public virtual DbSet<v_record> v_record { get; set; }
        public virtual DbSet<v_sg_affairs> v_sg_affairs { get; set; }
        public virtual DbSet<v_sing> v_sing { get; set; }
        public virtual DbSet<v_sysloginlog> v_sysloginlog { get; set; }
        public virtual DbSet<v_userexam> v_userexam { get; set; }
        public virtual DbSet<v_wjsw> v_wjsw { get; set; }
        public virtual DbSet<v_workpublish> v_workpublish { get; set; }
        public virtual DbSet<v_zxloginlog> v_zxloginlog { get; set; }
        public virtual DbSet<tpersons> tpersons { get; set; }
    }
}
