//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lb_classify
    {
        public lb_classify()
        {
            this.lb_affairsclassify = new HashSet<lb_affairsclassify>();
        }
    
        public int ID { get; set; }
        public string CLASSIFYNAME { get; set; }
        public int PROJECTID { get; set; }
        public int VALID { get; set; }
    
        public virtual ICollection<lb_affairsclassify> lb_affairsclassify { get; set; }
        public virtual lb_classifyproject lb_classifyproject { get; set; }
    }
}
