//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class linebusiness_count
    {
        public int ID { get; set; }
        public string VMIP { get; set; }
        public Nullable<int> VMCOUNT { get; set; }
        public Nullable<System.DateTime> LASTTIME { get; set; }
        public Nullable<int> VMID { get; set; }
    }
}
