//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lineweburl
    {
        public lineweburl()
        {
            this.lineelement = new HashSet<lineelement>();
        }
    
        public int ID { get; set; }
        public Nullable<int> LineID { get; set; }
        public string modURL { get; set; }
        public string modFormPageTitle { get; set; }
        public string modFormClass { get; set; }
        public string frameName { get; set; }
    
        public virtual linebusinesssys linebusinesssys { get; set; }
        public virtual ICollection<lineelement> lineelement { get; set; }
    }
}
