//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lineelement
    {
        public int ID { get; set; }
        public Nullable<int> lineweburlID { get; set; }
        public string ElementName { get; set; }
        public string ElementClass { get; set; }
        public string ElementType { get; set; }
    
        public virtual lineweburl lineweburl { get; set; }
    }
}
