//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class materials_details
    {
        public materials_details()
        {
            this.bg_takemat = new HashSet<bg_takemat>();
        }
    
        public int ID { get; set; }
        public int AFFAIRID { get; set; }
        public string MATINDEX { get; set; }
        public string MATNAME { get; set; }
        public int MATTYPE { get; set; }
        public int MATNUMBER { get; set; }
        public string REQUIRED { get; set; }
        public int MATGROUP { get; set; }
        public string REMARKS { get; set; }
        public string EXAMPLEPATH { get; set; }
        public int VALID { get; set; }
    
        public virtual affairs affairs { get; set; }
        public virtual ICollection<bg_takemat> bg_takemat { get; set; }
        public virtual dic_receivetype dic_receivetype { get; set; }
    }
}
