//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mtrecord
    {
        public int ID { get; set; }
        public int MTID { get; set; }
        public int CURRENTKEEPUSER { get; set; }
        public System.DateTime RECORDDATE { get; set; }
    
        public virtual materialtransfer materialtransfer { get; set; }
    }
}
