//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class repositoryanswers
    {
        public int AnswerID { get; set; }
        public Nullable<int> RepositoryID { get; set; }
        public string AnswerDesc { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<int> VALID { get; set; }
    
        public virtual repository repository { get; set; }
    }
}
