//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class repository_base_attachment
    {
        public int ID { get; set; }
        public int Repository_baseID { get; set; }
        public string AttachmentPath { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> VALID { get; set; }
    
        public virtual repository_base repository_base { get; set; }
    }
}
