//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_syinfo
    {
        public int ID { get; set; }
        public string MotherName { get; set; }
        public string MotherCard { get; set; }
        public string FatherName { get; set; }
        public string FatherCard { get; set; }
        public string ChilName { get; set; }
        public string ChilSex { get; set; }
        public string Attr { get; set; }
        public string ChilSum { get; set; }
        public Nullable<System.DateTime> ChilAddTime { get; set; }
        public Nullable<System.DateTime> ChilBirthTime { get; set; }
        public string ChilAddress { get; set; }
        public string ChilAddressInfo { get; set; }
        public string BirthAddress { get; set; }
        public string SYZ { get; set; }
        public string Contact { get; set; }
    }
}
