//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class repository_base
    {
        public repository_base()
        {
            this.repository_base_attachment = new HashSet<repository_base_attachment>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AffairID { get; set; }
        public string AffairCode { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<int> VALID { get; set; }
    
        public virtual affairs affairs { get; set; }
        public virtual ICollection<repository_base_attachment> repository_base_attachment { get; set; }
    }
}
