//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_userinfo
    {
        public int Id { get; set; }
        public string cardId { get; set; }
        public string attrName { get; set; }
        public string attrVal { get; set; }
        public string className { get; set; }
        public System.DateTime addTime { get; set; }
        public string PC { get; set; }
    }
}
