//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requestwindow
    {
        public int ID { get; set; }
        public Nullable<int> TOWNCODE { get; set; }
        public Nullable<int> COMMITTEE { get; set; }
        public Nullable<int> WINDOW { get; set; }
        public string MACHINECODE { get; set; }
        public Nullable<System.DateTime> REQUESTDATE { get; set; }
        public Nullable<bool> REQUESTISDEAL { get; set; }
    
        public virtual dic_committee dic_committee { get; set; }
        public virtual dic_town dic_town { get; set; }
    }
}
