//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class st_apply
    {
        public string ST_RESULT { get; set; }
        public string ST_ITEM_NAME { get; set; }
        public System.DateTime DT_APPLY_TIME { get; set; }
        public string ST_APPLY_PERSON { get; set; }
        public int ST_APPLY_ID { get; set; }
        public string CURRAFFAIRCODE { get; set; }
    }
}
