//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class st_exam
    {
        public st_exam()
        {
            this.st_user_exam = new HashSet<st_user_exam>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ea_paper { get; set; }
        public Nullable<System.DateTime> start_titme { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public Nullable<int> ea_user { get; set; }
        public string ea_user_name { get; set; }
    
        public virtual ICollection<st_user_exam> st_user_exam { get; set; }
        public virtual st_paper st_paper { get; set; }
    }
}
