//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class st_faq
    {
        public st_faq()
        {
            this.st_reply = new HashSet<st_reply>();
        }
    
        public int ID { get; set; }
        public Nullable<int> islocked { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
        public string fa_title { get; set; }
        public string fa_content { get; set; }
        public string fa_user { get; set; }
        public Nullable<int> fa_type { get; set; }
        public string fa_email { get; set; }
        public string fa_tell { get; set; }
        public string fa_mobile { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<int> isreply { get; set; }
        public Nullable<int> fa_userid { get; set; }
    
        public virtual ICollection<st_reply> st_reply { get; set; }
    }
}
