//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class st_paper
    {
        public st_paper()
        {
            this.st_exam = new HashSet<st_exam>();
            this.st_paperquestion = new HashSet<st_paperquestion>();
        }
    
        public int ID { get; set; }
        public string pa_title { get; set; }
        public Nullable<System.DateTime> pa_starttime { get; set; }
        public Nullable<System.DateTime> pa_endtime { get; set; }
        public Nullable<int> pa_time { get; set; }
        public Nullable<System.DateTime> add_titme { get; set; }
        public Nullable<int> pa_user { get; set; }
    
        public virtual ICollection<st_exam> st_exam { get; set; }
        public virtual ICollection<st_paperquestion> st_paperquestion { get; set; }
    }
}
