//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class st_paperquestion
    {
        public int ID { get; set; }
        public Nullable<int> pq_paper { get; set; }
        public Nullable<int> pq_question { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
    
        public virtual st_paper st_paper { get; set; }
        public virtual st_question st_question { get; set; }
    }
}
