//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class st_question
    {
        public st_question()
        {
            this.st_answer = new HashSet<st_answer>();
            this.st_paperquestion = new HashSet<st_paperquestion>();
            this.st_userfav = new HashSet<st_userfav>();
            this.st_user_exam = new HashSet<st_user_exam>();
        }
    
        public int ID { get; set; }
        public string qw_title { get; set; }
        public string qw_status { get; set; }
        public string qw_train { get; set; }
        public string qw_qf { get; set; }
        public Nullable<int> qw_level { get; set; }
        public string qw_tips { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
        public Nullable<decimal> qw_score { get; set; }
        public string qw_keys { get; set; }
        public int qw_ismul { get; set; }
        public Nullable<int> qw_dept { get; set; }
        public string qw_filter { get; set; }
        public Nullable<int> isValid { get; set; }
        public string qw_select { get; set; }
    
        public virtual dic_competentauth dic_competentauth { get; set; }
        public virtual ICollection<st_answer> st_answer { get; set; }
        public virtual ICollection<st_paperquestion> st_paperquestion { get; set; }
        public virtual ICollection<st_userfav> st_userfav { get; set; }
        public virtual ICollection<st_user_exam> st_user_exam { get; set; }
    }
}
