//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class st_reply
    {
        public int ID { get; set; }
        public Nullable<int> ry_userid { get; set; }
        public string ry_username { get; set; }
        public Nullable<System.DateTime> ry_titme { get; set; }
        public string ry_ip { get; set; }
        public string ry_content { get; set; }
        public Nullable<int> ry_faq { get; set; }
        public Nullable<int> parent_id { get; set; }
    
        public virtual st_faq st_faq { get; set; }
    }
}
