//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class st_user_exam
    {
        public int ID { get; set; }
        public string as_select { get; set; }
        public Nullable<System.DateTime> as_time { get; set; }
        public Nullable<int> as_question { get; set; }
        public Nullable<int> as_exam { get; set; }
        public Nullable<decimal> as_score { get; set; }
        public int as_status { get; set; }
        public int isRight { get; set; }
    
        public virtual st_exam st_exam { get; set; }
        public virtual st_question st_question { get; set; }
    }
}
