//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_user
    {
        public sy_user()
        {
            this.auditattachment = new HashSet<auditattachment>();
            this.notice = new HashSet<notice>();
            this.violateinfo = new HashSet<violateinfo>();
            this.violateattachment = new HashSet<violateattachment>();
            this.user_remark = new HashSet<user_remark>();
            this.userpower = new HashSet<userpower>();
            this.userright = new HashSet<userright>();
        }
    
        public int USERID { get; set; }
        public string USERNAME { get; set; }
        public string REALNAME { get; set; }
        public string USERPWD { get; set; }
        public int SEX { get; set; }
        public System.DateTime BIRTHDAY { get; set; }
        public string IDCARD { get; set; }
        public string CARDNUMBER { get; set; }
        public int ULEVEL { get; set; }
        public Nullable<int> UROLE { get; set; }
        public int COUNTIES { get; set; }
        public int TOWNS { get; set; }
        public int BUSINESS { get; set; }
        public int LASTLOGINLOGID { get; set; }
        public Nullable<System.DateTime> LASTLOGINTIME { get; set; }
        public int VALID { get; set; }
        public string FINGERCODE { get; set; }
        public Nullable<int> TRYLOGINTIME { get; set; }
        public Nullable<System.DateTime> LASTTRYDATETIME { get; set; }
        public Nullable<int> COMMITTEE { get; set; }
    
        public virtual ICollection<auditattachment> auditattachment { get; set; }
        public virtual dic_committee dic_committee { get; set; }
        public virtual dic_counties dic_counties { get; set; }
        public virtual dic_locdepartment dic_locdepartment { get; set; }
        public virtual dic_town dic_town { get; set; }
        public virtual dic_userlevel dic_userlevel { get; set; }
        public virtual dic_userrole dic_userrole { get; set; }
        public virtual ICollection<notice> notice { get; set; }
        public virtual ICollection<violateinfo> violateinfo { get; set; }
        public virtual ICollection<violateattachment> violateattachment { get; set; }
        public virtual ICollection<user_remark> user_remark { get; set; }
        public virtual ICollection<userpower> userpower { get; set; }
        public virtual ICollection<userright> userright { get; set; }
    }
}
