//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysmsgnotification
    {
        public int ID { get; set; }
        public Nullable<int> CURR_AFFAIRID { get; set; }
        public string MSGCONTENT { get; set; }
        public Nullable<int> MSGTYPE { get; set; }
        public Nullable<int> SENDER { get; set; }
        public Nullable<int> RECEIVER { get; set; }
    
        public virtual affairinfo affairinfo { get; set; }
        public virtual sysmsgtype sysmsgtype { get; set; }
    }
}
