//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transportfile
    {
        public int ID { get; set; }
        public Nullable<int> AFFAIRID { get; set; }
        public string FILEPATH { get; set; }
        public Nullable<int> TOWNCODE { get; set; }
        public string TRANSSTATUS { get; set; }
        public string ABOUT { get; set; }
    
        public virtual dic_town dic_town { get; set; }
    }
}
