//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_report
    {
        public int id { get; set; }
        public string cardid { get; set; }
        public string attrName { get; set; }
        public string attrVal { get; set; }
        public string attrTime { get; set; }
        public string UserName { get; set; }
        public string attrClass { get; set; }
        public string PC { get; set; }
        public Nullable<int> attrId { get; set; }
    }
}
