//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_affplan
    {
        public string PlanType { get; set; }
        public int CheckID { get; set; }
        public string Type { get; set; }
        public string Plan { get; set; }
        public string State { get; set; }
        public string ApplyAction { get; set; }
        public long ID { get; set; }
        public int AFFAIRID { get; set; }
        public string AFFAIRCODE { get; set; }
        public string AFFAIRNAME { get; set; }
        public string AF_ABBREVIATION { get; set; }
        public int AF_LEVEL { get; set; }
        public int AF_DEPARTMENT { get; set; }
        public float TIMELIMIT { get; set; }
        public int AF_PARENT { get; set; }
        public string AffairsLevelName { get; set; }
        public string AffairsDeptmentName { get; set; }
        public int VALID { get; set; }
    }
}
