//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_examquestion
    {
        public Nullable<decimal> Score { get; set; }
        public long Total { get; set; }
        public Nullable<decimal> RIGHTTotal { get; set; }
        public Nullable<decimal> ERRORTotal { get; set; }
        public int ID { get; set; }
        public string qw_title { get; set; }
        public string qw_status { get; set; }
        public string qw_train { get; set; }
        public string qw_qf { get; set; }
        public Nullable<int> qw_level { get; set; }
        public string qw_tips { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
        public Nullable<decimal> qw_score { get; set; }
        public string qw_keys { get; set; }
        public int qw_ismul { get; set; }
        public Nullable<int> qw_dept { get; set; }
        public string qw_filter { get; set; }
        public Nullable<int> isValid { get; set; }
        public string qw_select { get; set; }
    }
}
