//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_lines
    {
        public int LINEID { get; set; }
        public string modCoding { get; set; }
        public Nullable<int> VMID { get; set; }
        public string modName { get; set; }
        public string fullNamed { get; set; }
        public string modAutoLogin { get; set; }
        public string modImgName { get; set; }
        public string modUrl { get; set; }
        public string modFormLoginPageTi { get; set; }
        public string modFormMainPageTit { get; set; }
        public string modFormClass { get; set; }
        public string modtxtUserNameClas { get; set; }
        public string modtxtPwdClass { get; set; }
        public string modLoginBtnClass { get; set; }
        public string modLoginBtnName { get; set; }
        public int isValid { get; set; }
        public int SYSINDEX { get; set; }
        public int AFFAIRID { get; set; }
        public string AFFAIRCODE { get; set; }
    }
}
