//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_manager
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string Realame { get; set; }
        public int Isvalid { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<System.DateTime> LastExitTime { get; set; }
        public Nullable<int> TownId { get; set; }
        public int DicCom { get; set; }
        public string RoleText { get; set; }
        public string RoleValue { get; set; }
        public string TownName { get; set; }
        public string DicName { get; set; }
    }
}
