//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_material
    {
        public int ID { get; set; }
        public string CURR_AFFAIRCODE { get; set; }
        public int DEPARTMENTID { get; set; }
        public System.DateTime TAKEOUTDATE { get; set; }
        public Nullable<System.DateTime> GETBACKDATE { get; set; }
        public int TAKEOUTUSER { get; set; }
        public Nullable<int> GETBACKUSER { get; set; }
        public bool ISRETURN { get; set; }
        public string REMARK { get; set; }
        public string OPERATORNAME { get; set; }
        public string P_NAME { get; set; }
        public string AFFAIRNAME { get; set; }
        public string Time { get; set; }
    }
}
