//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_sg_affairs
    {
        public int AffairId { get; set; }
        public string AffairName { get; set; }
        public string AffairCode { get; set; }
        public int Available { get; set; }
        public string ConnectLine { get; set; }
        public string Policy { get; set; }
        public string Material { get; set; }
        public string Flow { get; set; }
    }
}
