//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_sing
    {
        public string AFFAIRNAME { get; set; }
        public int CURR_AFFAIRID { get; set; }
        public int AFFAIRID { get; set; }
        public int OPERATORID { get; set; }
        public string CURR_AFFAIRCODE { get; set; }
        public int FLOWRESULT { get; set; }
        public int NEXTFLOW { get; set; }
        public int NEXTPERSON { get; set; }
        public System.DateTime TRANSTIME { get; set; }
        public System.DateTime LASTTRANSTIME { get; set; }
        public int TRANSTYPE { get; set; }
        public int STATEOFAFFAIRS { get; set; }
        public string SATISFYDEGREE { get; set; }
        public string QUEUE_NUM { get; set; }
        public int VALID { get; set; }
        public Nullable<int> TOWNCODE { get; set; }
        public string USERNAME { get; set; }
        public string P_NAME { get; set; }
        public string Time { get; set; }
        public string FLOWCODE { get; set; }
        public int FLOWID { get; set; }
    }
}
