//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_workpublish
    {
        public string 开始时间_结束时间 { get; set; }
        public string 流程名称_状态 { get; set; }
        public string 处理单位 { get; set; }
        public string 处理人名称 { get; set; }
        public string 处理人账号 { get; set; }
        public string 处理人意见 { get; set; }
        public int 流程排序 { get; set; }
        public int 业务信息ID { get; set; }
        public int 流转工单ID { get; set; }
        public int id { get; set; }
    }
}
