//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class violateinfo
    {
        public violateinfo()
        {
            this.violateattachment = new HashSet<violateattachment>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PERSONBASE_ID { get; set; }
        public Nullable<int> CURR_AFFAIRID { get; set; }
        public Nullable<int> VIOLATEBEHAVIOR { get; set; }
        public string VIOLATEREASON { get; set; }
        public Nullable<System.DateTime> VIOLATETIME { get; set; }
        public Nullable<int> OPERATORID { get; set; }
        public string VERIFICATIONORG { get; set; }
        public Nullable<int> VALID { get; set; }
    
        public virtual affairinfo affairinfo { get; set; }
        public virtual dic_violatebehavior dic_violatebehavior { get; set; }
        public virtual personbase personbase { get; set; }
        public virtual sy_user sy_user { get; set; }
        public virtual ICollection<violateattachment> violateattachment { get; set; }
    }
}
