//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yu_yue
    {
        public int Id { get; set; }
        public Nullable<int> nid { get; set; }
        public string affair_name { get; set; }
        public string affair_code { get; set; }
        public Nullable<System.DateTime> created_time { get; set; }
        public string yu_yue_Number { get; set; }
        public string person { get; set; }
        public string id_number { get; set; }
        public string phonenum { get; set; }
        public string appt_date { get; set; }
        public string appt_date_new { get; set; }
        public Nullable<int> Towns { get; set; }
        public Nullable<int> yu_yue_state { get; set; }
        public string curr_affaircode { get; set; }
    }
}
