//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class znsgsitelog
    {
        public int ID { get; set; }
        public string MachineNumber { get; set; }
        public string LogDate { get; set; }
        public string LogTime { get; set; }
        public string Operation { get; set; }
        public string Remark { get; set; }
    }
}
