//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zxloginlog
    {
        public int ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public string USERNAME { get; set; }
        public string MODNAME { get; set; }
        public string AFFAIRCODE { get; set; }
        public string LOGINIP { get; set; }
        public Nullable<int> LOGINCOUNT { get; set; }
        public string LAST_LOGINTIME { get; set; }
        public string LAST_EXITTIME { get; set; }
    }
}
